
version: '3'
services:
  react-app:
    image: muqadasjaved433/my-react-app:latest
    container_name: react-app
    restart: always
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-app
